# syntax=docker/dockerfile:1

FROM rust:1.96-alpine

RUN cargo install --locked systemfd \
    && cargo install --locked cargo-watch

WORKDIR /app

EXPOSE 7878

CMD ["systemfd", "--no-pid", "-s", "http::7878", "--", "cargo", "watch", "--poll", "-x", "run"]
