CREATE TABLE "sessions" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "created_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_sessions_by_token_hash" ON "sessions" ("token_hash");
CREATE INDEX "index_sessions_by_user_id" ON "sessions" ("user_id");
CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
