CREATE TYPE "task_priority" AS ENUM ('none', 'low', 'medium', 'high', 'urgent');
CREATE TABLE "task_tags" (
    "task_id" BIGINT NOT NULL,
    "tag_id" BIGINT NOT NULL,
    PRIMARY KEY ("task_id", "tag_id")
);
CREATE INDEX "index_task_tags_by_task_id" ON "task_tags" ("task_id");
CREATE INDEX "index_task_tags_by_tag_id" ON "task_tags" ("tag_id");
CREATE TABLE "tasks" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "due_at" TIMESTAMPTZ(6),
    "completed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "priority" "task_priority" NOT NULL,
    "owner_id" BIGINT NOT NULL,
    "parent_id" BIGINT,
    "project_id" BIGINT,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_tasks_by_owner_id" ON "tasks" ("owner_id");
CREATE INDEX "index_tasks_by_parent_id" ON "tasks" ("parent_id");
CREATE INDEX "index_tasks_by_project_id" ON "tasks" ("project_id");
CREATE TABLE "tags" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "color" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "owner_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_tags_by_owner_id" ON "tags" ("owner_id");
CREATE TABLE "projects" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "archived_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "owner_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_projects_by_owner_id" ON "projects" ("owner_id");
